"""on cascade deleted

Revision ID: 4af9639495b8
Revises: ba267a87e06e
Create Date: 2023-08-04 09:55:24.701348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af9639495b8'
down_revision = 'ba267a87e06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('like_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('like_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('like_ibfk_2', 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('like_ibfk_1', 'user', ['author'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
