"""Added birthday field.

Revision ID: 54afc850ef0b
Revises: b2aef5eaf079
Create Date: 2023-08-02 12:48:26.824931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54afc850ef0b'
down_revision = 'b2aef5eaf079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
