"""comment model updated

Revision ID: 5fc8bbc4d1ab
Revises: 9df1d3fd039d
Create Date: 2023-08-05 20:56:59.907089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fc8bbc4d1ab'
down_revision = '9df1d3fd039d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_content', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
