"""comment model updated

Revision ID: 9df1d3fd039d
Revises: b8108eb1ee7f
Create Date: 2023-08-05 20:52:30.462872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df1d3fd039d'
down_revision = 'b8108eb1ee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_2', 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comment_ibfk_1', 'user', ['author'], ['id'], ondelete='CASCADE')

    op.drop_table('message')
    # ### end Alembic commands ###
