"""Initial migration.

Revision ID: b2aef5eaf079
Revises: 
Create Date: 2023-08-02 12:28:47.638616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2aef5eaf079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    op.drop_table('subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('metadata', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_subscription', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('feedback',
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
