"""post(image/picture_file) model updated

Revision ID: beec80995fef
Revises: dcf95c6ba0d6
Create Date: 2023-08-10 17:58:09.315366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beec80995fef'
down_revision = 'dcf95c6ba0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_file', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('picture_file')

    # ### end Alembic commands ###
