"""message model updated + chat model added

Revision ID: c13d0c493036
Revises: a54c3a1d8794
Create Date: 2023-08-09 00:20:06.261107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c13d0c493036'
down_revision = 'a54c3a1d8794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'])
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_ibfk_1', 'user', ['recipient_id'], ['id'])

    op.drop_table('chat_participants')
    op.drop_table('chat')
    # ### end Alembic commands ###
